site_name: Character DNA Addon
nav:
  - Getting Started: "index.md"
  - Terminology: "terminology.md"
  - FAQ: "faq.md"
  - Free Features:
    - Rig Instances: "free-features/rig-instances.md"
    - View Options: "free-features/view-options.md"
    - Face Board: "free-features/face-board.md"
    - Animation: "free-features/animation.md"
    - Output: "free-features/output.md"
  - Pro Features:
    - Converter: "pro-features/converter.md"
    # - Mesh Editor: "pro-features/mesh-editor.md"
    - Raw Editor: "pro-features/raw-editor.md"
    - Shape Key Editor: "pro-features/shape-key-editor.md"
    - RBF Editor: "pro-features/rbf-editor.md"
    - Backup Manager: "pro-features/backup-manager.md"
  - Workflows:
    - Append & Link: "workflows/append-link.md"
    - Mesh Wrapping: "workflows/mesh-wrapping.md"
    - Customizing Materials: "workflows/customizing-materials.md"
  - Contributing:
    - Development: "contributing/development.md"
    - Documentation: "contributing/documentation.md"
    - Testing: "contributing/testing.md"

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
